In [10]:
from sklearn.preprocessing import normalize
from sklearn.feature_extraction.text import *
from sklearn.cluster import KMeans
from itertools import combinations
import numpy as np

In [9]:
dim = 88
npt = 66
pts = np.random.randint(low=0, high=2, size=(npt, dim))
# pts
norm_pts = normalize(pts.astype(np.float))
dist = norm_pts.dot(norm_pts.T)
print 'average similarity:', np.mean(dist[np.triu_indices(npt,k=1)])

average similarity: 0.493664888871


In [3]:
def get_query_clusters(points, k):
    '''
    points [n,m] - array for n points with dimention m - encoded query
    '''
    # normalize input
    points = normalize(points.astype(np.float))
    # get similarity matrix (cosine distance)
    dist = points.dot(points.T)
    # initialize variables
    n_pt = len(points)
    cluster_old, cluster_new = np.ones(n_pt), np.zeros(n_pt)
    # special case, no clustering
    if k==1 or n_pt==1:        
        return np.zeros(n_pt), 1 if n_pt==1 else np.mean(dist[np.triu_indices(n_pt,k=1)])
    # randomly choose k starting centroids
    centroids = points[np.random.permutation(n_pt)[:k]]
    while not np.array_equal(cluster_old, cluster_new):
        cluster_old = cluster_new
        # get cluster index for each point
        cluster_new = np.argmax(points.dot(centroids.T), axis=1)
        # get new centroids, and within class mean distance/similarity
        centroids, in_dist = [], []
        for c in np.unique(cluster_new):
            pid = cluster_new==c
            # set new centroid as the one who has minimum total distance to rest of the points in the cluster
            cid = np.argmax(np.sum(dist[np.ix_(pid, pid)], axis=1))
            centroids.append(points[pid][cid])
            in_dist.append(1 if sum(pid)==1 else np.mean(dist[np.ix_(pid,pid)][np.triu_indices(sum(pid),k=1)]))
        centroids = np.array(centroids)
        # traditional way to get new centroid, not working well for cosine distance
#         centroids = normalize([np.mean(points[cluster_new==c], axis=0) for c in np.unique(cluster_new)])

    return cluster_new, np.mean(in_dist)


In [17]:
def query_characterizer(queries, similarity_limit = 0.9):
    '''
    queries - list of string for queries
    return - list of integers to indicate cluster for each query
    '''
    # vectorize queries
#     characterizer = CountVectorizer()
#     encoded_query = characterizer.fit_transform(queries)
    # find the optimal clusters based on minimum within cluster distance
    avg_sim, k = 0, 0
    while avg_sim < similarity_limit:
        k += 1
        clusters, avg_sim = get_query_clusters(queries, k)
        
    return clusters, k, avg_sim
    # for each cluster, assemble training points from its queries
    # for c in np.unique(clusters):


In [19]:
query_characterizer(pts,0.8)

(array([ 8, 20, 10, 14,  1,  8, 14, 15, 14,  6, 14, 18, 10, 10, 14,  3,  7,
         7, 10, 20, 12, 11,  9, 10, 14, 14,  5, 10, 10, 14,  0, 13, 17, 14,
        19, 10, 10, 10,  8,  8, 18, 15,  8, 13, 14,  9,  8, 10,  7, 13, 13,
        10, 10, 10,  9, 16,  7, 10, 10, 18, 10,  2, 10,  4, 10,  7], dtype=int64),
 21,
 0.81634124511092665)

In [8]:
# normalize(pts.astype(np.float))
get_query_clusters(pts,1)

(array([ 0.]), 1)

In [112]:
km = KMeans(20)
cluster = km.fit_predict(norm_pts)
in_dist = []
for c in np.unique(cluster):
    pid = cluster==c    
    in_dist.append(1 if sum(pid)==1 else np.mean(dist[np.ix_(pid,pid)][np.triu_indices(sum(pid),k=1)]))
print np.mean(in_dist)

0.644579618166


In [28]:
import pickle
savedData = 'UT_74_19243.pickle'
with open(savedData) as f: 
    feature, plan = pickle.load(f)

In [74]:
plan=np.array(plan)
# from sets import Set

In [67]:
n_plan = len(plan)
sim_click = [[plan[np.random.permutation(n_plan)], plan[np.random.permutation(n_plan)[0:np.random.randint(low=1, high=10)]]] 
             for i in range(8)]

In [79]:
n_plan, n_fea = feature.shape

In [120]:
# from scipy.sparse import *
a=lil_matrix((1,5))
# np.random.random_sample(5)

In [123]:
a= vstack([a, lil_matrix(np.random.random_sample(5))] ,format='lil')

In [125]:
a=csr_matrix(a[range(1,a.shape[0]),:])

In [126]:
a.toarray()

array([[ 0.18459087,  0.58896731,  0.18837221,  0.41953534,  0.38871448],
       [ 0.73644199,  0.45115154,  0.02206008,  0.5990885 ,  0.96838771],
       [ 0.10087744,  0.17272667,  0.74513651,  0.87360091,  0.17749498]])

In [110]:
b.toarray()

array([[ 0.67688549,  0.915354  ,  0.86653478,  0.22574209,  0.04491325],
       [ 0.90993134,  0.67798375,  0.09539874,  0.97191795,  0.54214246],
       [ 0.34596626,  0.10906454,  0.51046527,  0.0044819 ,  0.72640462]])

In [108]:
type(b)

scipy.sparse.csr.csr_matrix

In [117]:
feature.getrow(0)

<1x19243 sparse matrix of type '<type 'numpy.float64'>'
	with 3906 stored elements in LInked List format>

In [ ]:
fea