In [2]:
from sklearn.preprocessing import normalize
import numpy as np

In [287]:
dim = 28
npt = 3
pts = np.random.randint(low=0, high=2, size=(npt, dim))
# pts

In [288]:
norm_pts = normalize(pts.astype(np.float))

In [301]:
norm_pts.dot(norm_pts.T)[np.triu_indices(npt,k=1)].min()

0.58094750193111244

In [293]:
# norm_pts
norm_pts.dot(norm_pts.T)

array([[ 1.        ,  0.5809475 ,  0.6       ],
       [ 0.5809475 ,  1.        ,  0.64549722],
       [ 0.6       ,  0.64549722,  1.        ]])

In [89]:
centroid = normalize(np.mean(norm_pts, axis=0))
# centroid

In [90]:
centroid.dot(norm_pts.T)

array([[ 0.98974728,  0.96979645,  0.92218656]])

In [184]:

def get_clusters(points, k):
    '''
    points [n,m] - array for n points with dimention m
    '''
    # initialize variables
    points = normalize(points.astype(np.float))
    n_pt = len(points)
    cluster_old, cluster_new = np.ones(n_pt), np.zeros(n_pt)
    # randomly choose k starting centroids
    centroids = points[np.random.permutation(n_pt)[:k]]
    while not np.array_equal(cluster_old, cluster_new):       
        cluster_old = cluster_new
        # get cluster index for each point
        cluster_new = np.argmax(points.dot(centroids.T), axis=1)
        # get new centroids
        centroids = normalize([np.mean(points[cluster_new==c], axis=0) for c in np.unique(cluster_new)])
    return cluster_new

In [303]:
get_clusters(pts,2)

array([0, 0, 0], dtype=int64)

In [283]:
# normalize(pts.astype(np.float))
get_clusters(pts,2)

array([1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [122]:
clus=np.argmax(norm_pts.dot(cen.T), axis=1)
cen_new=normalize([np.mean(norm_pts[clus==c], axis=0) for c in np.unique(clus)])

In [125]:
np.sum((cen-cen_new)**2,axis=0)

array([ 0.06258162,  0.00998852])

In [137]:
np.random.randint(low=0,high=5,size=3)

array([4, 3, 4])

In [282]:
np.tile([1,2],(3,1))

array([[1, 2],
       [1, 2],
       [1, 2]])