In [268]:
from sklearn.feature_extraction.text import *
from sklearn.preprocessing import normalize
import numpy as np
# from sklearn.metrics.pairwise import pairwise_distances, distance_metrics, cosine_distances

from sklearn.preprocessing import OneHotEncoder
from pymongo import MongoClient, DESCENDING
from zipfile import ZipFile, ZIP_DEFLATED
from scipy.sparse import *
from scipy import stats
from sklearn import svm
from sets import Set
import numpy as np
import json, sys, os, time, re, datetime, itertools, pickle

In [216]:
test = ['this is a test query for aca w210 project', 'another query for characterization test', 'the third, query']
qVectorizer = CountVectorizer()

In [217]:
t1 = qVectorizer.fit_transform(test)

In [224]:
t1.getrow(0).getcol(0).data[0]

1

In [5]:
qVectorizer.vocabulary_

{u'aca': 0,
 u'another': 1,
 u'characterization': 2,
 u'for': 3,
 u'is': 4,
 u'project': 5,
 u'query': 6,
 u'test': 7,
 u'the': 8,
 u'third': 9,
 u'this': 10,
 u'w210': 11}

In [57]:
t2=qVectorizer.transform(['chris, froom'])
t5=normalize(t2.astype(np.float))

In [60]:
t2.data.size

0

In [63]:
t1.toarray()

array([[1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0]])

In [81]:
(t1.getrow(0)-t1.getrow(1)).toarray()[0]

array([ 1, -1, -1,  0,  1,  1,  0,  0,  0,  0,  1,  1])

In [82]:
(t1.getrow(0)-t1.getrow(1)).toarray()[0]**2

array([1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1])

In [90]:
t1.getrow(1).toarray()[0].T

array([0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0])

In [103]:
vNorm = Normalizer()

In [107]:
vNorm.fit_transform(t1.astype(np.float))

<3x12 sparse matrix of type '<type 'numpy.float64'>'
	with 16 stored elements in Compressed Sparse Row format>

In [142]:
t3=normalize(t1.astype(np.float))

In [111]:
t3.toarray

array([[ 0.35355339,  0.        ,  0.        ,  0.35355339,  0.35355339,
         0.35355339,  0.35355339,  0.35355339,  0.        ,  0.        ,
         0.35355339,  0.35355339],
       [ 0.        ,  0.4472136 ,  0.4472136 ,  0.4472136 ,  0.        ,
         0.        ,  0.4472136 ,  0.4472136 ,  0.        ,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.57735027,  0.        ,  0.57735027,  0.57735027,
         0.        ,  0.        ]])

In [120]:
t3.getrow(0).dot(t3.getrow(1).T)[0,0]

0.47434164902525683

In [143]:
t3.dot(t3.T).toarray()

array([[ 1.        ,  0.47434165,  0.20412415],
       [ 0.47434165,  1.        ,  0.25819889],
       [ 0.20412415,  0.25819889,  1.        ]])

In [151]:
t1.dot(t1.T).toarray() #data

array([[8, 3, 1],
       [3, 5, 1],
       [1, 1, 3]])

In [152]:
t1.dot(t1.T).data

array([1, 3, 8, 1, 5, 3, 3, 1, 1])

In [150]:
t3.getrow(0).dot(t3.T).data

array([ 0.20412415,  0.47434165,  1.        ])

In [154]:
pairwise_distances(t1)

array([[ 0.        ,  2.64575131,  3.        ],
       [ 2.64575131,  0.        ,  2.44948974],
       [ 3.        ,  2.44948974,  0.        ]])

In [158]:
cosine_distances(t3)

array([[ -2.22044605e-16,   5.25658351e-01,   7.95875855e-01],
       [  5.25658351e-01,  -2.22044605e-16,   7.41801110e-01],
       [  7.95875855e-01,   7.41801110e-01,  -2.22044605e-16]])

In [84]:
sample_diseases = ['Alzheimer', 'Glaucoma', 'Hypertension', 'diabetes', 'Obesophobia']

In [87]:
queries = []
for i in range(len(sample_diseases)):
    ind = np.random.permutation(len(sample_diseases))    
    queries.append(' '.join([sample_diseases[ind[j]] for j in range(i+1)]))

queries

['Glaucoma',
 'diabetes Obesophobia',
 'Obesophobia diabetes Alzheimer',
 'Glaucoma diabetes Alzheimer Hypertension',
 'Glaucoma Alzheimer diabetes Obesophobia Hypertension']

In [158]:
n_plan = 10
n_query = len(queries)
plans = {'plan'+str(i):np.random.rand(n_query) for i in range(n_plan)}

In [159]:
plans

{'plan0': array([ 0.93811278,  0.58271162,  0.95394552,  0.80454036,  0.11018708]),
 'plan1': array([ 0.88919069,  0.16683996,  0.78930152,  0.00480106,  0.91606525]),
 'plan2': array([ 0.36940453,  0.24450371,  0.16581709,  0.4306663 ,  0.08946527]),
 'plan3': array([ 0.216611  ,  0.78077445,  0.00587427,  0.49085104,  0.60828484]),
 'plan4': array([ 0.24474484,  0.94817901,  0.57678063,  0.49719357,  0.19672252]),
 'plan5': array([ 0.5207491 ,  0.22891773,  0.87431569,  0.45162895,  0.36615036]),
 'plan6': array([ 0.34839321,  0.12876407,  0.24339172,  0.33677754,  0.17774903]),
 'plan7': array([ 0.09833196,  0.14241926,  0.4645087 ,  0.88936566,  0.03179588]),
 'plan8': array([ 0.01307044,  0.97979089,  0.56878078,  0.09273202,  0.52906352]),
 'plan9': array([ 0.07127443,  0.2516136 ,  0.81273463,  0.76027092,  0.10753063])}

In [278]:
%reload_ext autoreload
%autoreload 2
from letor_online import *

In [263]:
letor = letor_online(queries, plans, 0.5)

In [245]:
{p:(r[0]+r[3])/2 for p,r in plans.items()}


{'plan0': 0.87132656774931716,
 'plan1': 0.44699587474961461,
 'plan2': 0.40003541305357987,
 'plan3': 0.35373101734116608,
 'plan4': 0.37096920602008571,
 'plan5': 0.48618902213141824,
 'plan6': 0.3425853738102273,
 'plan7': 0.49384881023406274,
 'plan8': 0.052901234049672285,
 'plan9': 0.41577267274640556}

In [164]:
queries

['Glaucoma',
 'diabetes Obesophobia',
 'Obesophobia diabetes Alzheimer',
 'Glaucoma diabetes Alzheimer Hypertension',
 'Glaucoma Alzheimer diabetes Obesophobia Hypertension']

In [264]:
letor.get_rank('Alzheimer Alzheimer Glaucoma  Glaucoma Obesophobia ')

return 4 closest match query with index: [0, 2, 3, 4]


{'plan0': 0.66543124905590512,
 'plan1': 0.67486627996924053,
 'plan2': 0.24721658829970228,
 'plan3': 0.34035334495071257,
 'plan4': 0.37183081892923597,
 'plan5': 0.55004567625678602,
 'plan6': 0.26792686666955995,
 'plan7': 0.34844434682697129,
 'plan8': 0.32746338077379988,
 'plan9': 0.42574124363813126}

In [267]:
letor.learnt_query

['Glaucoma',
 'diabetes Obesophobia',
 'Obesophobia diabetes Alzheimer',
 'Glaucoma diabetes Alzheimer Hypertension',
 'Glaucoma Alzheimer diabetes Obesophobia Hypertension']

In [269]:
local = False
if local:
    client = MongoClient('fc8iasm01', 27017)
    plan_col = client.aca.plan
    drug_col = client.aca.drug
else:
    client = MongoClient('ec2-54-153-83-172.us-west-1.compute.amazonaws.com', 27017)
    plan_col = client.plans.plans
    drug_col = client.formularies.drugs
    prov_col = client.providers.providers
    faci_col = client.providers.facilities

all_plan = drug_col.distinct('plans.plan_id')
all_drug = drug_col.distinct('rxnorm_id')

print '%s: using %s Mongo, total drug: %d, total plan: %d, total provider: %d' %(
    logTime(), 'local' if local else 'aws', len(all_drug), len(all_plan), prov_col.count())
# client.formularies.scollection_names()
# client.providers.collection_names()

NameError: name 'logTime' is not defined

In [270]:
# print '%s: plan document: %d' %(logTime(), plan_col.count())
# print '%s: drug document: %d' %(logTime(), drug_col.count())
# print '%s: provider document: %d' %(logTime(), prov_col.count())
# print '%s: facility document: %d' %(logTime(), faci_col.count())
# print '%s: unique plan_id: %d' %(logTime(), len(all_plan))
# print '%s: unique rxnorm_id: %d' %(logTime(), len(all_drug))

# # multi_plan = [1 for p in plan_col.aggregate([{"$group": {"_id":"$plan_id", "count":{"$sum":1}}}]) if p['count']>1]
# # print '%s: plans with multiple documents: %d' %(logTime(), sum(multi_plan))

# # multi_drug = [1 for p in drug_col.aggregate([{"$group": {"_id":"$rxnorm_id", "count":{"$sum":1}}}]) if p['count']>1]
# # print '%s: drugs with multiple documents: %d' %(logTime(), sum(multi_drug))

state_id = np.unique([i[5:7] for i in all_plan])
# print '%s: states in the plan: %s' %(logTime(), ', '.join(state_id))
print state_id

[u'AK' u'AL' u'AR' u'AZ' u'CO' u'DE' u'FL' u'GA' u'HI' u'IA' u'IL' u'IN'
 u'KS' u'KY' u'LA' u'MA' u'ME' u'MI' u'MN' u'MO' u'MS' u'MT' u'NC' u'ND'
 u'NE' u'NH' u'NJ' u'NM' u'NV' u'OH' u'OK' u'OR' u'PA' u'SC' u'SD' u'TN'
 u'TX' u'UT' u'VA' u'WA' u'WI' u'WV' u'WY']


In [276]:
state = 'OR'
ids = [p for p in all_plan if state in p]
plan_rank = {p:np.random.rand(n_query) for p in ids}
saveName = 'runtime_data_%s.pickle' %(state)
with open(saveName, 'w') as f:
    pickle.dump([plan_rank, queries], f)

In [277]:
savedData = 'runtime_data_OR.pickle'
with open(savedData) as f: 
    plan_ranks, queries = pickle.load(f)
    
letor = letor_online(queries, plan_ranks)
letor.get_rank('glaucoma')

return 1 closest match query with index: [0]


{u'10091OR0360004': 0.27269680380577255,
 u'10091OR0360005': 0.53221866323457001,
 u'10091OR0360006': 0.27196859797037365,
 u'10091OR0360007': 0.0185071392711601,
 u'10091OR0360008': 0.37363693686144306,
 u'10091OR0360009': 0.39362838868829575,
 u'10091OR0360010': 0.8792201056147454,
 u'10091OR0360011': 0.77201212915975681,
 u'10091OR0360012': 0.95222971904859299,
 u'10091OR0370002': 0.23496719086139939,
 u'10091OR0370003': 0.79860131365684106,
 u'10091OR0370004': 0.52763101461465023,
 u'10091OR0380003': 0.88779859014682549,
 u'10091OR0380004': 0.062592313384498444,
 u'10091OR0380005': 0.19530577889816536,
 u'10091OR0380006': 0.96924289387695572,
 u'10091OR0380007': 0.087657052111195344,
 u'10091OR0380008': 0.26730044834286426,
 u'10091OR0380009': 0.5806000219621843,
 u'10091OR0380010': 0.29769644663642569,
 u'10091OR0380011': 0.9002721933376443,
 u'10091OR0380012': 0.381221744093585,
 u'10091OR0380013': 0.35516418332022259,
 u'10091OR0380014': 0.63367146082659032,
 u'10091OR0390003': 